### ISSUE TITLE
Missing Dependency - Getting an error at try to rename with cosmic-ui

### ISSUE THREAD

**Issue by AlphaTechnolog** [CosmicNvim/cosmic-ui#1]
At call:

```lua
require('cosmic-ui').rename()
```

In my attach function, with code like this:

```lua
function bufmap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end

bufmap('n', 'gn', '<cmd>lua require("cosmic-ui").rename()<cr>', { noremap = true, silent = true })
```

It shows an error at call it function in my file:

```
Error at executing vim.schedule lua callback: vim.lua:435: Chunk is not an array with one or two strings
```

Investigating, the file and the line is:

```lua
-- ~/.local/share/nvim/site/pack/packer/start/cosmic-ui/lua/cosmic-ui/rename/handler.lua:30
vim.notify(msg, vim.log.levels.INFO, { title = ('Rename: %s -> %s'):format(currName, new_word) })
```

I don't know what I am doing wrong

> NOTE: Sorry for my english

**Comment by mattleong** [comment]
Hmm.. I will resolve at this ASAP. 

In the meantime, you can add nvim-notify as a plugin dependency and that error should go away.

**Comment by mattleong** [comment]
Hi @AlphaTechnolog, I was able to reproduce and find a fix for this, which is now pushed up!

Will close this soon unless you let me know otherwise :)

**Comment by AlphaTechnolog** [comment]
Very thank you @mattleong I will checkout it, and then if all is successfully, I will close this!

Thank you very much for your time!

**Comment by AlphaTechnolog** [comment]
Note: I have installed nvim-notify in my neovim config

**Comment by AlphaTechnolog** [comment]
Thank you so much, I test it and all works successfully!
