### ISSUE TITLE
Renaming identifiers with 23 (or more) characters

### ISSUE THREAD

**Issue by jeff-dh** [CosmicNvim/cosmic-ui#4]
I just wanted to rename a function with a name of the length of 23 characters and when calling `cosmic-ui.rename()` a -- seemingly -- empty textbox popup.

It turned out that the textbox actually was not empty but was "scrolled" and the whole identifier was "scrolled out of" the textbox. Hitting the left arrow key once fixed it, buuuuuuut.... this is at least confusing.

Same for identifiers longer than 23 characters, when renaming a 25 character identifier 2 characters -- seemingly -- show up in the textbox.

In both cases would I would expect the textbox to be completely filled and only truncated on the left side.

**Comment by jeff-dh** [comment]
I already found the issue, I'm gonna commit a pr soon.

**Comment by mattleong** [comment]
@jeff-dh did you end up finding a fix? Idk if I've experienced/noticed this issue

**Comment by jeff-dh** [comment]
Just deleted my fork yesterday on github but luckely still had a local copy.... there you go....

**Comment by mattleong** [comment]
@jeff-dh Mind submitting a pull request?
